### ISSUE TITLE
Part4 transactions.go 区块链保存交易的时候SetID失败，tx.ID 为空

### ISSUE THREAD

**Issue by kisskillkiss** [liuchengxu/blockchain-tutorial#10]
你好，冒昧打扰
非常感谢你的“blockchain-tutorial”教程，我在Part4 的时候发现一个问题：

保存的区块链里的数据tx.ID 设置失败，数据都是[]byte{nil},导致测试多个address多笔交易send之后，FindUnspentTransactions()会丢失除最后一次输出的币，
经排查找到原因，transaction.go Line 45
func (tx Transaction) SetID() 应该为
func (tx *Transaction) SetID() 才能真正设置ID成功

**Comment by liuchengxu** [comment]
欢迎提 PR 修改，由于时间原因，这个系列的后面几篇都没有能把代码跑一下 :)。

**Comment by liuchengxu** [comment]
已  merge，#11 。
